name: substation_manager_pro
description: "Substation Manager Pro: A modern, robust, and scalable application for managing electrical substations."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 1. Backend & Authentication
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.1.0
  cloud_functions: ^5.0.4

  # 2. State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  visibility_detector: ^0.4.0+2

  # 3. Local Database (Stable Isar v3)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # 4. UI & Responsive Layout
  responsive_framework: ^1.5.1
  cupertino_icons: ^1.0.8

  # 5. Models & Code Generation (Runtime)
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.0.0
  widgets_to_image: ^2.0.1
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.40
  excel: ^4.0.6
  open_filex: ^4.7.0
  dropdown_search: ^6.0.2
  csv: ^6.0.0
  camera: ^0.11.2
  geolocator: ^14.0.2
  flutter_colorpicker: ^1.1.0
  connectivity_plus: ^6.0.5
  flutter_flavorizr: ^2.2.3
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generators - All Compatible Versions
  build_runner: ^2.4.7 # Compatible with isar_generator
  freezed: ^2.5.2 # Compatible with both generators
  json_serializable: ^6.3.1
  riverpod_generator: ^2.4.0 # Downgraded as suggested
  isar_generator: ^3.1.0+1
  flutter_lints: ^6.0.0
  flutter_form_builder: ^10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_logo.webp
    - assets/states_cities.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
