// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI_2xk-tN1JASjYT3vsvOcmZne41Q1oJ0',
    appId: '1:1044356634454:web:2b3a9386e0b692f66f68f7',
    messagingSenderId: '1044356634454',
    projectId: 'electrical-substation-manager',
    authDomain: 'electrical-substation-manager.firebaseapp.com',
    storageBucket: 'electrical-substation-manager.firebasestorage.app',
    measurementId: 'G-PM0MG83N8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgksADSlHOoy5gJrLtBH2sMhAwA_4qrpM',
    appId: '1:1044356634454:android:5dda29b54bba44e36f68f7',
    messagingSenderId: '1044356634454',
    projectId: 'electrical-substation-manager',
    storageBucket: 'electrical-substation-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ZvkRkmjof52QoHSlht5BHT_fixnF8dw',
    appId: '1:1044356634454:ios:ec1f16a8c541a86e6f68f7',
    messagingSenderId: '1044356634454',
    projectId: 'electrical-substation-manager',
    storageBucket: 'electrical-substation-manager.firebasestorage.app',
    iosBundleId: 'com.example.electricalSubstationManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ZvkRkmjof52QoHSlht5BHT_fixnF8dw',
    appId: '1:1044356634454:ios:ec1f16a8c541a86e6f68f7',
    messagingSenderId: '1044356634454',
    projectId: 'electrical-substation-manager',
    storageBucket: 'electrical-substation-manager.firebasestorage.app',
    iosBundleId: 'com.example.electricalSubstationManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI_2xk-tN1JASjYT3vsvOcmZne41Q1oJ0',
    appId: '1:1044356634454:web:0da61b70af51736a6f68f7',
    messagingSenderId: '1044356634454',
    projectId: 'electrical-substation-manager',
    authDomain: 'electrical-substation-manager.firebaseapp.com',
    storageBucket: 'electrical-substation-manager.firebasestorage.app',
    measurementId: 'G-ZETR9QL6TS',
  );

}